@startuml
skinparam classAttributeIconSize 0

rectangle "User Aggregate" {
class User {
  -id: UUID
  -nome: String
  -email: String
  -password: String
  -telefone: String
  +login()
  +criarConta()
  +cancelarConta()
  +alterarInformacoes()
}

class Role {
  -id: UUID
  -nome: String <<CLIENTE | PARK_MANAGER | ADMIN>>
}
class PaymentMethod {
   -id: UUID
   -tipo: String
   -detalhes: String
   +alterar()
 }
}

rectangle "Vehicle Aggregate" {
class Carro {
  -matricula: String
  -marca: String
  -modelo: String
  -aprovado: Boolean
  +alterarInformacoes()
}


class PedidoDeRegisto {
  -id: UUID
  -dataPedido: Date
  -estado: String <<aprovado|rejeitado|pendente>>
}
}


rectangle "Park Aggregate" {
class Parque {
  -id: UUID
  -nome: String
  -localizacao: String
  -capacidade: int
  -portaoAberto: Boolean
  +abrirPortao()
  +fecharPortao()
}

class Lugar {
  -id: UUID
  -numero: int
  -disponivel: Boolean
}
}

' Relações
User "1" -- "0..*" Role : tem >
User "1" -- "0..*" Carro : possui >
User "1" -- "0..1" PaymentMethod
User "1" -- "0..*" PedidoDeRegisto : submete >

PedidoDeRegisto "1" -- "1" Carro : refere >

Parque "1" -- "0..*" Lugar : contém >

Role "CLIENTE" ..> PedidoDeRegisto : submete >
Role "PARK_MANAGER" ..> Parque : gere >
Role "PARK_MANAGER" ..> PedidoDeRegisto : aprova/rejeita >
Role "ADMIN" ..> Role : cria >

@enduml
