version: "3"
services:
  myapp:
    image: test
    env_file:
      - ParkingSystem/.env
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - ip6net

networks:
  ip6net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8::/64
